### ISSUE TITLE
Return isNewUser if user doesn't have a primaryClass

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#1]
It would be great if the API returned instantly that the user doesn't have a primary class. This would help reduce the amount of loading screens when redirecting from service to service

**Comment by prawich-th** [comment]
Sure, no problems!

**Comment by prawich-th** [comment]
I have completed the request.

changed file:
- [Controller auth.ts](https://github.com/SS-Developers/SS-APIs/blob/main/src/controllers/auth.ts)
