### ISSUE TITLE
Glance returning lunch as next period ahead of time.

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#10]
**Describe the bug 🔎**

The endpoint of "/getGlance" returns lunch as the next period lunch when the current period is the first period of the day.

**To Reproduce 🧪**

Use an assumption class and wait for the first class of school (classes after this aren't observed yet).

**Expected behavior 🔥**

Should've been the class after the first period.

## **Screenshot 🖼️ (optional)**

![image](https://user-images.githubusercontent.com/87472782/169727359-f9afaa97-7eb9-4e11-9cc2-96a7514e35a8.png)
![image](https://user-images.githubusercontent.com/87472782/169727813-14164e71-3da3-4ebd-893f-3eeac7bf0e27.png)

**Comment by prawich-th** [comment]
This issue has been resolved. the API has rewritten the find class before lunch algorithm.
