### ISSUE TITLE
Glance fails to return completly

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#11]
**Describe the bug 🔎**

The endpoint "/getGlance" fails to return anything for classes from Newton and Essence.

**To Reproduce 🧪**

Try setting primaryClass as any school from the above and look at glance.

**Expected behavior 🔥**

The endpoint should've returned something or a just returned an understandable error message.

**Screenshot 🖼️ (optional)**

![image](https://user-images.githubusercontent.com/87472782/169727906-674c7ff3-551d-4bc4-96b0-813265cee6f7.png)

**Comment by prawich-th** [comment]
This issue has been resolved the issue originated from the part that handles homeroom.
