### ISSUE TITLE
Endpoint for signing up shouldn't require account type

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#4]
**Describe the bug**
This isn't really a but more of a security flaw.  a user shouldn't be able to select which type of account they'd want to signup for. The front end should only create normal user accounts. Since JS in the browser is vulnerable I think the API shouldn't require an accType

**Error Code**
![image](https://user-images.githubusercontent.com/87472782/166894485-38122314-9dbd-4f0b-8f5c-5283e43e270f.png)

**Comment by prawich-th** [comment]
the issue has been addressed, this issue will be resolve asap

**Comment by prawich-th** [comment]
<img width="1440" alt="Screen Shot 2565-05-05 at 17 18 27" src="https://user-images.githubusercontent.com/90727258/166904406-0aeab439-0ea7-48ff-bbd8-7626de601632.png">

the issue has been resolved
