### ISSUE TITLE
Books to bring tomorrow

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#5]
![image](https://user-images.githubusercontent.com/87472782/167856995-2d815022-d37e-4c12-8a13-f4df898eaec7.png)

**The API returns which books to bring and remove tomorrow based on whether the school uses books or digital books.**

---
## 📚 Which books to bring and remove
API returns the list of classes that are not in today's timetable but on the following day **(Books to bring)** and returns the list of classes that are in today's timetable but not on the following day's timetable  **(Books to remove)**

## 🔭 Following subjects
If the school mostly uses a digital book system, Timetables will default the option to the following subjects which will only return the following day's subjects without the removed part.

API returns every subject on the following day

## ✅ An option to switch modes on preferences page

There should be three options, Books to bring, Following Subjects and off. These options should be on the endpoint which manages user configurations

**Comment by prawich-th** [comment]
this has been resolved.

now if `curClass` & `nextClass` are `FTD` the GET `/timetables/getGlance` should return
```jsonc
// timetableData, etc.

"prepType": "book" /*or "subject" or "hide"*/,
"prep": {
    "toAdd": [/*Formatted Class Name*/],
    "toRemove": [/*Formatted Class Name*/],
}

// Note: if the prepType == "subject" prep object will not contain "toRemove" and if it's "hide" there will be no prep object at all.

```
