### ISSUE TITLE
Returning the glance periods too early

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#6]
## **Describe the bug 🔎**

The API returns the current period and the next period after midnight.

## **To Reproduce 🧪**

Wait till midnight and see the current period and next period appearing

## **Expected behavior 🔥**

Glance shouldn't return the current period and the next period until the first period starts

## **Screenshot 🖼️ (optional)**

![image](https://user-images.githubusercontent.com/87472782/167909241-7a91d162-60ef-4dcc-a3e4-fc0ea9106846.png)

**Comment by prawich-th** [comment]
Sorry but the clock says 24:19 is that even possible?

**Comment by prawich-th** [comment]
anyways this issue will be fix asap

**Comment by prawich-th** [comment]
This issue has been resolved, Thank you for making Timetable API better tools for everyone.

now the API will return BFS 1 hour before the school starts ex.
if the school begins at 8:00 

|time|curClass|nextClass|
|:----|:----------|:-----|
|7:00 - 7:59| BFS | PHY |
|0:00 - 6:59| FTD | FTD |

> If you think the FTD should be replaced with any other code or a new code please let me know.
