### ISSUE TITLE
For every period before lunch, API doesn't return lunch as next period.

### ISSUE THREAD

**Issue by Jiraties** [SS-Developers/SS-APIs#9]
## **Describe the bug 🔎**
The API returns the next period as the period after lunch. 
The bug was encountered with the primary class as a class from Assumption College (still haven't tested if this happens to other schools other than Assumption College).

## **To Reproduce 🧪**

Wait till the period before lunch at a class from Assumption College.

## **Expected behavior 🔥**

Should return the next period being lunch, not the class after lunch.

## **Screenshot 🖼️ (optional)**

![image](https://user-images.githubusercontent.com/87472782/169441454-31c94dc1-27a2-4291-9c8c-31ffa92c045b.png)

**Comment by prawich-th** [comment]
During the period before lunch, the timetable API should return LUC now. The problem was with the new algorithm that Timetables API uses.
